kind: pipeline
type: docker
name: default
steps:
    - name: blog-web
      image: appleboy/drone-ssh
      environment:
          ENV_VARS:
              from_secret: env_vars
      settings:
          host: 118.25.23.125
          username: benjamin
          key:
              from_secret: ssh_key
          port: 22
          command_timeout: 2m
          envs: [ENV_VARS]
          script:
              - cd /home/benjamin/htdocs
              - '[ -d ./blog-web ] && rm -rf ./blog-web'
              # 这一行很重要，因为没有的话，第一次克隆就会失败
              - GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone -q git@git.tch59.cn:benjamin59/blog-web.git ./blog-web
              - cd blog-web
              - echo "$${ENV_VARS}" > .env
              - 'source ~/.zshrc; pnpm i && pnpm build && pm2 restart ecosystem.config.js && pm2 save'
