import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SiteHeader } from "@/components/header";
import { SiteFooter } from "@/components/footer";
import { BgforCircle } from "@/components/BgAnimate";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Benjamin59",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        inter.variable
      )}>
        <div className="relative flex min-h-dvh flex-col bg-background custom-gradient">
          <BgforCircle />
          <SiteHeader />
          <main className="flex-1 pt-20 p-5">{children}</main>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
